### ISSUE TITLE
Gulpfile should not need to be present in working directory

### ISSUE THREAD

**Issue by ghost** [KabbAmine/gulp-vim#2]
Hi, thanks for your work. I think this plugin should be smart enough to check up the directory tree until reaching some indicative project root marker (I'm sure you could copy a good implementation from elsewhere as it's common vim plugin functionality) to find a project's gulpfile. Or can it already do this?

**Comment by KabbAmine** [comment]
Hi.

I really don't see the need specially when we have multiple gulpfiles, 
usually we start (g)vim in our project directory and the gulpfile is in 
the root (I'm not an advanced developer so maybe I'm wrong).
Anyway, the command `:GulpFile` is here, but doesn't work with paths 
(e.g `:GulpFile foo/bar/gulpfile.coffee`), so I'll fix that.

**Comment by ghost** [comment]
I see your points. But if I'm not mistaken, gulp will actually traverse up the directory tree itself to find the gulpfile. So when I run gulp tasks using your plugin from gulpfile sub-directory, it barks at me and says gulpfile not found, when in fact the command would have worked! And multiple gulp files doesn't really change anything... Just traverse up starting from current directory (or buffer directory... would be a cool feature if configurable) until you find one.

E.g. I frequently find myself opening a file from a directory for a quick change and then looking to run some gulp tasks. The plugin is not that helpful if I must manually set the gulpfile path.

Of course it's your call but I think it would be an awesome feature. I'd offer to submit a PR but have no idea when/if I'd be able to

**Comment by KabbAmine** [comment]
I understand your points and I agree (As you said, a configurable 
option(s) will be great (cwd/buffer, a limited depth...)).
I'll dig into it then.

**Comment by KabbAmine** [comment]
@dawnofthedev Check the last commit 75cb4be, and let me know if its working good for you.

**Comment by KabbAmine** [comment]
Looks good enough for me, I close the issue.

@dawnofthedev Feel free to open it again if needed.

**Comment by ghost** [comment]
@KabbAmine sorry for the delay. I tried it and it suits my usage perfectly. Nicely done.

**Comment by KabbAmine** [comment]
Great then :smiley:
