### ISSUE TITLE
Add unite gulp source

### ISSUE THREAD

**Issue by ghost** [KabbAmine/gulp-vim#3]
Hi, thanks for your work. Similar to how you make gulp tasks available for ctrlp, it would be awesome if you added a unite source for them too as unite was pretty much built for this kind of thing.

**Comment by KabbAmine** [comment]
Hi again :smiley:

Sure that will be great, I'm not personally an Unite user so I will 
implement that when I'll have time.
A PR is always welcome :smiley: (`:GulpTasks` is all what we need).

**Comment by ghost** [comment]
Hi yes I will try to write one then, but it will take some time. Aside, you should try Unite. People will often claim ctrlp is better as a fuzzy file finder but that's just if you are lazy about it and Unite is way more powerful. You can see some unite stuff in my dotfiles.

**Comment by KabbAmine** [comment]
Great then, take your time.

I've tried Unite and ctrlp-like plugins many times, and I always went 
back to ctrlp, a strong habit I presume.
There is also the very good fzf (I'm using it in my shell), check it out.
